from .login_form import LoginForm
from .signup_form import SignUpForm
from .profile_form import ProfileForm
from .review_form import ReviewForm
from .collection_form import CollectionForm
from .film_form import FilmForm
from .no_upload_profile_form import NoUploadProfileForm
from .edit_film_form import UpdateFilmForm
from .poster_form import PosterForm
from .still_form import StillForm
